<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="<?= $this->basePath('css/login.css') ?>">
</head>

<body style="background-image: url(<?= $this->basePath('img/login.jpeg') ?>);">
    <div class="login-container">
        <h1>Login</h1>
        <?php if (isset($error)): ?>
        <div class="error-message"><?= $error ?></div>
        <?php endif; ?>

        <form method="post" action="<?= $this->url('login') ?>">
            <div class="form-group">
                <label for="email">Email:</label>
                <input type="text" name="email" id="email" required>
            </div>

            <div class="form-group">
                <label for="password">Password:</label>
                <input type="password" name="password" id="password" required>
            </div>

            <button type="submit">Login</button>
        </form>

        <div class="additional-options">
            <a href="#">Forgot Password?</a>
            <!-- Replace with your Google login integration -->
            <a href="<?= $this->url('register') ?>"> register</a>
        </div>
    </div>
</body>

</html>