<div class="content" style="margin-top:80px;">
    <input type="text" id="basePath" style="display:none;" value="<?= $this->basePath() ?>">
    <div class="page-header">
        <div class="page-title">
            <h4>Customers List</h4>
            <h6>Manage your Customers</h6>
        </div>
        <div class="page-btn">
            <a id="addCustomer" class="btn btn-added">
                <img src="<?= $this->basePath('img/icons/plus.svg') ?>" alt="img" class="me-1">Add Customer</a>
        </div>
    </div>

    <div class="card" id="filter_inputs">
        <div class="card-body pb-0">
            <div class="row">
                <div class="col-lg-2 col-sm-6 col-12">
                    <div class="form-group">
                        <input type="text" placeholder="Enter Customer Code">
                    </div>
                </div>
                <div class="col-lg-2 col-sm-6 col-12">
                    <div class="form-group">
                        <input type="text" placeholder="Enter Customer Name">
                    </div>
                </div>
                <div class="col-lg-2 col-sm-6 col-12">
                    <div class="form-group">
                        <input type="text" placeholder="Enter Phone Number">
                    </div>
                </div>
                <div class="col-lg-2 col-sm-6 col-12">
                    <div class="form-group">
                        <input type="text" placeholder="Enter Email">
                    </div>
                </div>
                <div class="col-lg-1 col-sm-6 col-12  ms-auto">
                    <div class="form-group">
                        <a class="btn btn-filters ms-auto"><img src="assets/img/icons/search-whites.svg" alt="img"></a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="table-responsive">
        <table class="table  datanew">
            <thead>
                <tr>
                    <th>
                        <label class="checkboxs">
                            <input type="checkbox" id="select-all">
                            <span class="checkmarks"></span>
                        </label>
                    </th>
                    <th>Customer Name</th>
                    <!-- <th>code</th> -->
                    <!-- <th>Customer</th> -->
                    <th>Phone</th>
                    <th>email</th>
                    <th>Address</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->AllCustomers as $row){
// dd($row);
                ?>
                <tr>
                    <td>
                        <label class="checkboxs">
                            <input type="checkbox">
                            <span class="checkmarks"></span>
                        </label>
                    </td>
                    <td> <?= $row->getName(); ?>
                    </td>
                    <td> <?= $row->getPhone(); ?></td>

                    <td><a href="<?= $row->getEmail(); ?>">
                            <?= $row->getEmail(); ?></a>
                    </td>

                    <td>
                        <?php
                        //  var_dump($row->getId());
                                     $address = $row->getAddress();
                                     $words = explode(' ', $address);
                                     $chunks = array();
                                    for ($i = 0; $i < count($words); $i += 4) {
                                        $chunks[] = implode(' ', array_slice($words, $i, 4));
                                    }
                                     $formattedAddress = implode('<br>', $chunks);
                                        ?>
                        <?= $formattedAddress; ?>
                    </td>

                    <td>
                        <a class="editbtn" data-item-id="<?= $row->getId() ?>"
                            data-item-name="<?= htmlspecialchars($row->getName()) ?>"
                            data-item-email="<?= htmlspecialchars($row->getEmail()) ?>"
                            data-item-phone="<?= htmlspecialchars($row->getPhone()) ?>"
                            data-item-ice="<?= htmlspecialchars($row->getICE()) ?>"
                            data-item-address="<?= htmlspecialchars($row->getAddress()) ?>"
                            data-item-bank="<?= htmlspecialchars($row->getBank()) ?>"
                            data-item-note="<?= htmlspecialchars($row->getNote()) ?>"
                            data-item-customercode="<?= htmlspecialchars($row->getCustomercode()) ?>"
                            data-item-bankname="<?= htmlspecialchars($row->getBankname()) ?>"
                            data-item-maxamount="<?= htmlspecialchars($row->getMaxPurchaseAmount()) ?>">
                            <img src="<?= $this->basePath('img/icons/edit.svg') ?>" alt="Edit">
                        </a>


                        <a href="#" class="deletebtn" data-item-id="<?= $row->getId() ?>">

                            <img src="<?= $this->basePath('img/icons/delete.svg') ?>" alt="Edit">
                        </a>





                        <!-- <a href="#" class="  deletebtn">
                            <img src="<?= $this->basePath('img/icons/delete.svg') ?>" alt="img"
                                data-item-id="<?=  htmlspecialchars($row->getId())?>">
                        </a> -->
                        <!-- <button class="deletebtn btn btn-danger" type="button"> delete</button> -->
                    </td>
                </tr>


                <?php }?>

            </tbody>
        </table>
    </div>
</div>
</div>






<div class="modal fade" id="addCustomerModal" tabindex="-1" method="post" aria-labelledby="addCustomerModal"
    aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Add New Customer</h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close"><span
                        aria-hidden="true">×</span></button>
            </div>
            <form enctype="multipart/form-data" id="addCustomerform">
                <div class="modal-body">
                    <div class="row">

                        <div class="col-lg-6 col-sm-12 col-12">
                            <div class="form-group">
                                <label>Name</label>
                                <div class="input-group">
                                    <input type="text" name="Name" required id="Name" placeholder="Customer Name"
                                        class="form-control">
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6 col-sm-12 col-12">
                            <div class="form-group">
                                <label>email</label>
                                <input type="text" name="email" id="email" placeholder="Customer Email">
                            </div>
                        </div>

                        <div class="col-lg-6 col-sm-12 col-12">
                            <div class="form-group">
                                <label>phone</label>
                                <div class="input-group">
                                    <input type="text" name="phone" required id="phone" placeholder="Customer Phone"
                                        class="form-control">
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6 col-sm-12 col-12">
                            <div class="form-group">
                                <label>address</label>
                                <input type="text" name="address" required id="address" placeholder="Customer Address">
                            </div>
                        </div>

                        <div class="col-lg-6 col-sm-12 col-12">
                            <div class="form-group">
                                <label>ICE</label>
                                <div class="input-group">
                                    <input type="text" name="ICE" id="ICE" placeholder="Customer ICE"
                                        class="form-control">
                                </div>
                            </div>
                        </div>

                        <div class="col-lg-6 col-sm-12 col-12">
                            <div class="form-group">
                                <label>Bank Account</label>
                                <input type="text" name="Bank" id="Bank" placeholder="Customer Bank Account">
                            </div>
                        </div>


                        <div class="col-lg-6 col-sm-12 col-12">
                            <div class="form-group">
                                <label>Bank Name</label>
                                <div class="input-group">
                                    <input type="text" name="bankname" id="bankname" placeholder="Customer Bank Name"
                                        class="form-control">
                                </div>
                            </div>
                        </div>

                        <div class="col-lg-6 col-sm-12 col-12">
                            <div class="form-group">
                                <label>Customer Code</label>
                                <input type="text" name="Bank" id="Bank" placeholder="Customer Code">
                            </div>
                        </div>



                        <div class="col-lg-6 col-sm-12 col-12">
                            <div class="form-group">
                                <label>Max Amount</label>
                                <div class="input-group">
                                    <input type="text" name="maxamount" id="maxamount" placeholder="Max Purchase Amount"
                                        class="form-control">
                                </div>
                            </div>
                        </div>




                        <div class="col-lg-12">
                            <div class="form-group">
                                <label>Note</label>
                                <textarea class="form-control" name="Note" id="Note" placeholder="Note"></textarea>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" id="addbtn" class="btn btn-submit">Submit</button>
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                </div>
            </form>
        </div>
    </div>
</div>



<div class="modal fade" id="editCustomerModal" tabindex="-1" aria-labelledby="editCustomerModalLabel"
    aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="editCustomerModalLabel">Edit Customer</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form id="editCustomerForm">
                <div class="modal-body">
                    <input type="hidden" id="customerId" name="customerId">
                    <div class="row">
                        <div class="col-lg-6 col-sm-12 col-12">
                            <div class="form-group">
                                <label>Name</label>
                                <input type="text" name="name" id="editName" placeholder="Customer Name"
                                    class="form-control">
                            </div>
                        </div>
                        <div class="col-lg-6 col-sm-12 col-12">
                            <div class="form-group">
                                <label>Email</label>
                                <input type="text" name="email" id="editEmail" placeholder="Customer Email"
                                    class="form-control">
                            </div>
                        </div>
                        <div class="col-lg-6 col-sm-12 col-12">
                            <div class="form-group">
                                <label>Phone</label>
                                <input type="text" name="phone" id="editPhone" placeholder="Customer Phone"
                                    class="form-control">
                            </div>
                        </div>
                        <div class="col-lg-6 col-sm-12 col-12">
                            <div class="form-group">
                                <label>Address</label>
                                <input type="text" name="address" id="editAddress" placeholder="Customer Address"
                                    class="form-control">
                            </div>
                        </div>
                        <div class="col-lg-6 col-sm-12 col-12">
                            <div class="form-group">
                                <label>ICE</label>
                                <input type="text" name="ICE" id="editICE" placeholder="Customer ICE"
                                    class="form-control">
                            </div>
                        </div>
                        <div class="col-lg-6 col-sm-12 col-12">
                            <div class="form-group">
                                <label>Bank Account</label>
                                <input type="text" name="Bank" id="editBank" placeholder="Customer Bank Account"
                                    class="form-control">
                            </div>
                        </div>



                        <div class="col-lg-6 col-sm-12 col-12">
                            <div class="form-group">
                                <label>Bank Name</label>
                                <div class="input-group">
                                    <input type="text" name="bankname" id="editbankname"
                                        placeholder="Customer Bank Name" class="form-control">
                                </div>
                            </div>
                        </div>

                        <div class="col-lg-6 col-sm-12 col-12">
                            <div class="form-group">
                                <label>Customer Code</label>
                                <input type="text" name="customercode" id="editcustomercode"
                                    placeholder="Customer Code">
                            </div>
                        </div>



                        <div class="col-lg-6 col-sm-12 col-12">
                            <div class="form-group">
                                <label>Max Amount</label>
                                <div class="input-group">
                                    <input type="text" name="maxamount" id="editmaxamount"
                                        placeholder="Max Purchase Amount" class="form-control">
                                </div>
                            </div>
                        </div>

                        <div class="col-lg-12">
                            <div class="form-group">
                                <label>Note</label>
                                <textarea class="form-control" name="Note" id="editNote" placeholder="Note"></textarea>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" id="editSubmitBtn" class="btn btn-primary">Save changes</button>
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                </div>
            </form>
        </div>
    </div>
</div>


<!-- Modal -->
<div class="modal fade" id="deleteCustomerModal" tabindex="-1" role="dialog" aria-labelledby="modelTitleId"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Delete Customer</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <form id="deleteCustomerForm" method="post">
                    <input type="text" name="idrow" id="idrow" class="form-control hidden">
            </div>
            <div class="modal-body">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary cancelbtn" data-dismiss="modal">Cancel</button>
                <button type="submit" class="btn btn-primary">Confirme</button>
            </div>
            </form>
        </div>
    </div>
</div>
<?= $this->inlineScript()->prependFile($this->basePath('js/jquery-3.6.0.min.js'));?>

<?php  $this->inlineScript() 
         ->appendFile($this->basePath('js/customers/scriptecustomers.js'));