<div class="content" style="margin-top: 80px;">
    <div class="page-header">
        <div class="page-title">
            <h4>Add Company</h4>
            <h6>Company Info</h6>
        </div>
    </div>

    <div class="card">
        <div class="card-body">
            <form id="formAddCompany" method="post" enctype="multipart/form-data">

                <div class="row">

                    <div class="col-lg-3 col-sm-6 col-12">
                        <div class="form-group">
                            <label>Company Name</label>
                            <input type="text" name="CompanyName" id="CompanyName" class="form-control" required>
                        </div>
                    </div>

                    <div class="col-lg-3 col-sm-6 col-12">
                        <div class="form-group">
                            <label>Logo</label>
                            <input type="file" class="form-control" name="Logo" id="Logo">
                        </div>
                    </div>

                    <div class="col-lg-3 col-sm-6 col-12">
                        <div class="form-group">
                            <label>Language</label>
                            <input type="text" name="Language" id="Language" class="form-control">
                        </div>
                    </div>

                    <div class="col-lg-3 col-sm-6 col-12">
                        <div class="form-group">
                            <label>SKU Format</label>
                            <input type="text" name="SkuFormat" id="SkuFormat" class="form-control">
                        </div>
                    </div>

                    <div class="col-lg-3 col-sm-6 col-12">
                        <div class="form-group">
                            <label>BL Format</label>
                            <input type="text" name="blformat" id="blformat" class="form-control">
                        </div>
                    </div>

                    <div class="col-lg-3 col-sm-6 col-12">
                        <div class="form-group">
                            <label>Invoice Format</label>
                            <input type="text" name="invoiceformat" id="invoiceformat" class="form-control">
                        </div>
                    </div>

                    <div class="col-lg-3 col-sm-6 col-12">
                        <div class="form-group">
                            <label>Estimate Format</label>
                            <input type="text" name="Esformat" id="Esformat" class="form-control">
                        </div>
                    </div>

                    <div class="col-lg-3 col-sm-6 col-12">
                        <div class="form-group">
                            <label>ICE</label>
                            <input type="text" name="ICE" id="ICE" class="form-control">
                        </div>
                    </div>

                    <div class="col-lg-3 col-sm-6 col-12">
                        <div class="form-group">
                            <label>Tax in (%)</label>
                            <input type="text" name="TAX" id="TAX" class="form-control">
                        </div>
                    </div>

                    <div class="col-lg-3 col-sm-6 col-12">
                        <div class="form-group">
                            <label>Dark Mode</label>
                            <select class="form-control" name="DarkMode" id="DarkMode">
                                <option value="off">Off</option>
                                <option value="on">On</option>
                            </select>
                        </div>
                    </div>

                    <div class="col-lg-3 col-sm-6 col-12">
                        <div class="form-group">
                            <label>Currency</label>
                            <input type="text" name="Currency" id="Currency" class="form-control">
                        </div>
                    </div>

                    <div class="col-lg-3 col-sm-6 col-12">
                        <div class="form-group">
                            <label>Country</label>
                            <input type="text" name="Country" id="Country" class="form-control">
                        </div>
                    </div>

                    <div class="col-lg-3 col-sm-6 col-12">
                        <div class="form-group">
                            <label>Company City</label>
                            <input type="text" name="CompanyCity" id="CompanyCity" class="form-control">
                        </div>
                    </div>

                    <div class="col-lg-3 col-sm-6 col-12">
                        <div class="form-group">
                            <label>Company Address</label>
                            <input type="text" name="CompanyAddress" id="CompanyAddress" class="form-control">
                        </div>
                    </div>

                    <div class="col-lg-3 col-sm-6 col-12">
                        <div class="form-group">
                            <label>Company Phone</label>
                            <input type="text" name="CompanyPhone" id="CompanyPhone" class="form-control">
                        </div>
                    </div>

                    <div class="col-lg-3 col-sm-6 col-12">
                        <div class="form-group">
                            <label>Company Email</label>
                            <input type="email" name="CompanyEmail" id="CompanyEmail" class="form-control">
                        </div>
                    </div>

                    <div class="col-lg-3 col-sm-6 col-12">
                        <div class="form-group">
                            <label>Code Postal</label>
                            <input type="text" name="codepostal" id="codepostal" class="form-control">
                        </div>
                    </div>

                    <div class="col-lg-3 col-sm-6 col-12">
                        <div class="form-group">
                            <label>President And CEO</label>
                            <input type="text" name="CEO" id="CEO" class="form-control" placeholder="PDG">
                        </div>
                    </div>

                    <div class="col-lg-3 col-sm-6 col-12">
                        <div class="form-group">
                            <label>Id. Prof (C.N.S.S.)</label>
                            <input type="text" name="cnss" id="cnss" class="form-control">
                        </div>
                    </div>

                    <div class="col-lg-3 col-sm-6 col-12">
                        <div class="form-group">
                            <label>Id. Prof (Patent)</label>
                            <input type="text" name="Patent" id="Patent" class="form-control">
                        </div>
                    </div>

                    <div class="col-lg-3 col-sm-6 col-12">
                        <div class="form-group">
                            <label>Id. prof (R.C.)</label>
                            <input type="text" name="RC" id="RC" class="form-control">
                        </div>
                    </div>

                    <div class="col-lg-3 col-sm-6 col-12">
                        <div class="form-group">
                            <label>Prof (I.F.)</label>
                            <input type="text" name="IF" id="IF" class="form-control">
                        </div>
                    </div>

                    <div class="col-lg-3 col-sm-6 col-12">
                        <div class="form-group">
                            <label>Legal Entity Type</label>
                            <select name="legalEntityType" id="legalEntityType" class="form-control">
                                <option value="sarl">SARL (Limited Liability Company)</option>
                                <option value="sarl_a">SARL-AU (Single-Member Limited Liability Company)</option>
                                <option value="sa">SA (Public Limited Company)</option>
                                <option value="snc">SNC (General Partnership)</option>
                                <option value="sca">SCA (Partnership Limited by Shares)</option>
                                <option value="scp">SCP (Professional Civil Company)</option>
                                <option value="groupe">Group</option>
                            </select>
                        </div>
                    </div>

                    <div class="col-lg-3 col-sm-6 col-12">
                        <div class="form-group">
                            <label>Company Status</label>
                            <?php if(empty($this->idcompany) ){  ?>
                            <input type="text" class="hidden" name="CompanyStatus" value="actif" id="CompanyStatus">
                            <input type="text" disabled value="actif">
                            <?php }else{ ?>
                            <input type="text" class="hidden" name="CompanyStatus" value="desable" id="CompanyStatus">
                            <input type="text" disabled value="desable">
                            <?php } ?>
                        </div>
                    </div>

                    <div class="col-lg-3 col-sm-6 col-12">
                        <div class="form-group">
                            <label>Created By</label>
                            <input type="text" disabled name="creator" id="creator"
                                value="<?php echo $this->creator; ?>" class="form-control ">

                            <input type="text" name="creator" id="creator" value="<?php echo $this->creator; ?>"
                                class="form-control hidden">
                        </div>
                    </div>

                    <div class="col-lg-12">
                        <button type="submit" class="btn btn-submit me-2">Submit</button>
                        <a href="companylist.html" class="btn btn-cancel">Cancel</a>
                    </div>

                </div>

            </form>
        </div>
    </div>

</div>

<!-- <?= $this->inlineScript()->appendFile($this->basePath('js/setting/scriptsetting.js')); ?> -->

<?= $this->inlineScript()
               
                ->appendFile($this->basePath('js/setting/scriptaddcompany.js'));              
?>