<div class="content" style="margin-top: 80px;">
    <div class="page-header">
        <div class="page-title">
            <h4>Edit Company</h4>
            <h6>Company info</h6>
        </div>
    </div>

    <div class="card">
        <div class="card-body">
            <form id="formAddProduct" method="post" enctype="multipart/form-data">

                <div class="row">
                    <?php  foreach ($this->companyinfo as $setting){ 
                        // dd($setting);
                        ?>
                    <div class="col-lg-3 col-sm-6 col-12">
                        <div class="form-group">
                            <label>Company Name</label>
                            <input type="text" value="<?=  $setting['companyName']?>" name="CompanyName"
                                id="CompanyName">
                        </div>
                    </div>
                    <div class="col-lg-3 col-sm-6 col-12">
                        <div class="form-group">
                            <label>Logo</label>
                            <input type="file" class="form-control" name="Logo" id="Logo"
                                value="<?=   $setting['logo'] ?>">
                        </div>
                    </div>
                    <div class="col-lg-3 col-sm-6 col-12">
                        <div class="form-group">
                            <label>Language</label>
                            <input type="text" name="Language" id="Language" value="<?=  $setting['language']   ?>">
                        </div>
                    </div>
                    <div class="col-lg-3 col-sm-6 col-12">
                        <div class="form-group">
                            <label>SKU Format</label>
                            <input name="SkuFormat" id="SkuFormat" class="form-control"
                                value="<?=  $setting['skuFormat']   ?>">
                        </div>
                    </div>

                    <div class="col-lg-3 col-sm-6 col-12">
                        <div class="form-group">
                            <label>BL Format</label>
                            <input type="text" name="blformat" id="blformat" value="<?=  $setting['blformat']   ?>">
                        </div>
                    </div>


                    <div class="col-lg-3 col-sm-6 col-12">
                        <div class="form-group">
                            <label>Invoice Format</label>
                            <input type="text" name="invoiceformat" id="invoiceformat"
                                value="<?=  $setting['invoiceformat'] ?>">
                        </div>
                    </div>


                    <div class="col-lg-3 col-sm-6 col-12">
                        <div class="form-group">
                            <label>ICE</label>
                            <input type="text" name="ICE" id="ICE" value="<?= $setting['ICE']?>">
                        </div>
                    </div>
                    <div class="col-lg-3 col-sm-6 col-12">
                        <div class="form-group">
                            <label>Dark Mode</label>

                            <select class="form-control" name="DarkMode" id="DarkMode">
                                <option value="off">Off</option>
                                <option value="on">On</option>
                            </select>
                            <!-- <input type="text" name="DarkMode" id="DarkMode" value="<?=  $setting['darkMode']   ?>"> -->
                        </div>
                    </div>
                    <div class="col-lg-3 col-sm-6 col-12">
                        <div class="form-group">
                            <label>Currency</label>
                            <input name="Currency" id="Currency" class="form-control"
                                value="<?=  $setting['currency']   ?>">
                        </div>
                    </div>
                    <div class="col-lg-3 col-sm-6 col-12">
                        <div class="form-group">
                            <label>Country</label>
                            <input name="Country" id="Country" class="form-control"
                                value="<?=  $setting['country']   ?>">
                        </div>
                    </div>
                    <div class="col-lg-3 col-sm-6 col-12">
                        <div class="form-group">
                            <label>Company City</label>
                            <input name="CompanyCity" id="CompanyCity" class="form-control"
                                value="<?=  $setting['companyCity']   ?>">
                        </div>
                    </div>
                    <div class="col-lg-3 col-sm-6 col-12">
                        <div class="form-group">
                            <label>Company Address</label>
                            <input name="CompanyAddress" id="CompanyAddress" class="form-control"
                                value="<?=  $setting['companyAddresse']   ?>">
                        </div>
                    </div>
                    <div class="col-lg-3 col-sm-6 col-12">
                        <div class="form-group">
                            <label>Company Phone</label>
                            <input type="text" name="CompanyPhone" id="CompanyPhone"
                                value="<?=  $setting['companyPhone']   ?>">
                        </div>
                    </div>
                    <div class="col-lg-3 col-sm-6 col-12">
                        <div class="form-group">
                            <label>Company Email</label>
                            <input class="form-control" type="email" name="CompanyEmail" id="CompanyEmail"
                                value="<?=  $setting['companyEmail']   ?>">
                        </div>
                    </div>








                    <div class="col-lg-3 col-sm-6 col-12">
                        <div class="form-group">
                            <label>Code Postal</label>
                            <input type="text" name="codepostal" id="codepostal" value="<?= $setting['codepostal']?>">
                        </div>
                    </div>
                    <div class="col-lg-3 col-sm-6 col-12">
                        <div class="form-group">
                            <label>President And CEO </label>
                            <input class="form-control" type="text" placeholder="PDG" name="CEO" id="CEO"
                                value="<?= $setting['CEO']?>">
                        </div>
                    </div>




                    <div class="col-lg-3 col-sm-6 col-12">
                        <div class="form-group">
                            <label>Id.Prof (C.N.S.S.)</label>
                            <input type="text" name="cnss" id="cnss" value="<?= $setting['cnss']?>">
                        </div>
                    </div>
                    <div class="col-lg-3 col-sm-6 col-12">
                        <div class="form-group">
                            <label>Id. Prof (Patent)</label>
                            <input class="form-control" type="text" name="Patent" id="Patent"
                                value="<?= $setting['Patent']?>">
                        </div>
                    </div>









                    <div class="col-lg-3 col-sm-6 col-12">
                        <div class="form-group">
                            <label>Id. prof (R.C.)</label>
                            <input type="text" name="RC" id="RC" value="<?= $setting['RC']?>">
                        </div>
                    </div>
                    <div class="col-lg-3 col-sm-6 col-12">
                        <div class="form-group">
                            <label>Prof (I.F.)</label>
                            <input class="form-control" type="text" name="IF" id="IF" value="<?= $setting['NIF']?>">
                        </div>
                    </div>
                    <div class="col-lg-3 col-sm-6 col-12">
                        <div class="form-group">
                            <label> Legal entity type</label>

                            <select name="legalEntityType" class="form-control" id="legalEntityType"
                                value="<?= $setting['legalEntityType']?>">
                                <option value="sarl">SARL (Limited Liability Company)</option>
                                <option value="sarl_a">SARL-AU (Single-Member Limited Liability Company)</option>
                                <option value="sa">SA (Public Limited Company)</option>
                                <option value="snc">SNC (General Partnership)</option>
                                <option value="sca">SCA (Partnership Limited by Shares)</option>
                                <option value="scp">SCP (Professional Civil Company)</option>
                                <option value="groupe">Group</option>
                            </select>
                        </div>
                    </div>








                    <div class="col-lg-3 col-sm-6 col-12">
                        <div class="form-group">
                            <label>Company Status</label>
                            <input type="text" disabled value="<?=  $setting['companyStatus']   ?>">
                        </div>
                    </div>

                    <div class="col-lg-3 col-sm-6 col-12">
                        <div class="form-group">
                            <label>Created By :</label>
                            <input disabled type="text" name="creator" id="creator"
                                value="<?=  $setting['fullname']   ?>">
                        </div>
                    </div>
                    <div class="col-lg-12">
                        <button type="submit" class="btn btn-submit me-2">Submit</button>
                        <a href="productlist.html" class="btn btn-cancel">Cancel</a>
                    </div>
                </div>
                <?php }?>
            </form>
        </div>
    </div>

</div>


<?= $this->inlineScript()     
                ->appendFile($this->basePath('js/setting/scriptsetting.js'));              
?>