<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Select Company</title>
    <style>
    body {
        display: flex;
        justify-content: center,  !important;
        align-items: center;
        height: 100vh;
        margin: 0;
        background-color: #f0f0f0;
        font-family: Arial, sans-serif;
    }

    .container {
        text-align: center;
        background: #fff;
        padding: 20px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        border-radius: 10px;
    }

    .container select {
        padding: 10px;
        width: 300px;
        font-size: 16px;
        margin-top: 10px;
        text-align: center;
        /* Center text inside the select box */
        text-align-last: center;
    }
    </style>
</head>

<body>
    <div class="container">
        <h1>Select Company</h1>
        <form action="<?= $this->basePath('settings/changecompany') ?>" method="post" enctype="multipart/form-data">
            <select name="idcompany" id="idcompany">
                <option>------------------------Select------------------------</option>
                <?php foreach( $getAllcompany as $row ){?>
                <option value="<?= $row["id"]; ?>"><?= $row["companyName"] ?></option>
                <?php } ?>


            </select>
            <button type="submit">change</button>
        </form>
    </div>
</body>

</html>