 <!-- <div class="page-wrapper"> -->
 <div class="content" style="margin-top:80px;">
     <div class="page-header">
         <div class="page-title">
             <h4>Product Add</h4>
             <h6>Create new product</h6>
         </div>
     </div>

     <div class="card">
         <div class="card-body">
             <form id="formAddProduct" method="post" enctype="multipart/form-data">
                 <div class="row">
                     <div class="col-lg-3 col-sm-6 col-12">
                         <div class="form-group">
                             <label>Product Name</label>
                             <input type="text" name="ProductName" id="ProductName">
                         </div>
                     </div>
                     <div class="col-lg-3 col-sm-6 col-12">
                         <div class="form-group">
                             <label>Category</label>
                             <select class="select" name="Category" id="Category">
                                 <option>Choose Category</option>
                                 <option value="Computers">Computers</option>
                             </select>
                         </div>
                     </div>
                     <div class="col-lg-3 col-sm-6 col-12">
                         <div class="form-group">
                             <label>Sub Category</label>
                             <select class="select" name="SubCategory" id="SubCategory">
                                 <option>Choose Sub Category</option>
                                 <option value="Fruits">Fruits</option>
                             </select>
                         </div>
                     </div>
                     <div class="col-lg-3 col-sm-6 col-12">
                         <div class="form-group">
                             <label>Brand</label>
                             <select class="select" name="Brand" id="Brand">
                                 <option>Choose Brand</option>
                                 <option value="Brand">Brand</option>
                             </select>
                         </div>
                     </div>
                     <div class="col-lg-3 col-sm-6 col-12">
                         <div class="form-group">
                             <label>Unit</label>
                             <select class="select" name="Unit" id="Unit">
                                 <option>Choose Unit</option>
                                 <option value="Unit">Unit</option>
                             </select>
                         </div>
                     </div>
                     <div class="col-lg-3 col-sm-6 col-12">
                         <div class="form-group">
                             <label>SKU</label>
                             <input type="text" name="SKU" id="SKU" value="<?= $this->newsku ?>">
                         </div>
                     </div>
                     <div class="col-lg-3 col-sm-6 col-12">
                         <div class="form-group">
                             <label>Minimum Qty</label>
                             <input type="text" name="Minimum" id="Minimum">
                         </div>
                     </div>
                     <div class="col-lg-3 col-sm-6 col-12">
                         <div class="form-group">
                             <label>Quantity</label>
                             <input type="text" name="Quantity" id="Quantity">
                         </div>
                     </div>
                     <div class="col-lg-12">
                         <div class="form-group">
                             <label>Description</label>
                             <textarea name="Description" id="Description" class="form-control"></textarea>
                         </div>
                     </div>
                     <div class="col-lg-3 col-sm-6 col-12">
                         <div class="form-group">
                             <label>Tax</label>
                             <select class="select" name="Tax" id="Tax">
                                 <option>Choose Tax</option>
                                 <option value="2">2%</option>
                             </select>
                         </div>
                     </div>
                     <div class="col-lg-3 col-sm-6 col-12">
                         <div class="form-group">
                             <label>Discount Type</label>
                             <select class="select" name="Discount" id="Discount">
                                 <option>Percentage</option>
                                 <option value="10">10%</option>
                                 <option value="20">20%</option>
                             </select>
                         </div>
                     </div>
                     <div class="col-lg-3 col-sm-6 col-12">
                         <div class="form-group">
                             <label>Price</label>
                             <input type="text" name="Price" id="Price">
                         </div>
                     </div>
                     <div class="col-lg-3 col-sm-6 col-12">
                         <div class="form-group">
                             <label> Status</label>
                             <select class="select" name="Status" id="Status">
                                 <option value="Closed">Closed</option>
                                 <option value="Open">Open</option>
                             </select>
                         </div>
                     </div>
                     <div class="col-lg-12">
                         <div class="form-group">
                             <label> Product Image</label>
                             <div class="image-upload">
                                 <input type="file" name="image" id="image">
                                 <div class="image-uploads">
                                     <img src="<?= $this->basePath('img/icons/upload.svg') ?>" alt="img">
                                     <h4>Drag and drop a file to upload</h4>
                                 </div>
                             </div>
                         </div>
                     </div>
                     <div class="col-lg-12">
                         <button type="submit" class="btn btn-submit me-2">Submit</button>
                         <a href="productlist.html" class="btn btn-cancel">Cancel</a>
                     </div>
                 </div>
             </form>
         </div>
     </div>

 </div>