<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<?= $this->doctype();?>


<html lang="en">

<head>
    <meta charset="utf-8">
    <?= $this->headTitle('Inventory')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>
    <!-- <?= $this->basePath('img/laminas-logo.svg') ?> -->
    <?= $this->headLink([
                        'rel' => 'shortcut icon',
                        'type' => 'image/vnd.microsoft.icon',
                        'href' => $this->basePath() . '/img/logo-small.png'
                    ])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->appendStylesheet($this->basePath('css/bootstrap.min.css'))
            ->appendStylesheet($this->basePath('css/animate.css'))
            ->appendStylesheet($this->basePath('plugins/fontawesome/css/fontawesome.min.css'))
            ->appendStylesheet($this->basePath('plugins/fontawesome/css/all.min.css')) 
            ->appendStylesheet($this->basePath('css/dataTables.bootstrap4.min.css'))
            ->appendStylesheet($this->basePath('plugins/select2/css/select2.min.css'))
            ->appendStylesheet($this->basePath('plugins/owlcarousel/owl.carousel.min.css'))
            ->appendStylesheet($this->basePath('css/dashboard.css'))
            ->appendStylesheet($this->basePath('css/costumalert.css'))
            ?>
</head>

<body>
    <!-- Custom alert box -->
    <div id="overlay"></div>
    <div id="customAlert" style="background-color:  rgba(0,0,0,0.0);">
        <a onclick="closeCustomAlert()">

            <img style="height:300px; width:300px" id="customAlertMessage"
                src="<?= $this->basePath('img/sucess.gif') ?>" alt="">

        </a>
        <!-- <button>Close</button> -->
    </div>
    <div class="container" style="background-color:   ; margin-left:20%;">
        <?= $this->content ?>

        <div id="global-loader">
            <div class="whirly-loader"> </div>
        </div>
        <?php if (!empty($_SESSION["user"])){?>
        <!-- <style>
        .logo-text {
            font-size: auto;
            font-weight: bold;
            color: #343a40;
            /* Dark color for text */
            font-family: 'Arial', sans-serif;

        }
        </style> -->
        <style>
        .logo-container {
            display: inline-block;
        }

        .logo-text {
            font-size: auto;
            font-size: 1rem;
            font-weight: bold;
            /* color: #343a40; */
            color: #ff9f4;
            font-family: 'Arial', sans-serif;
            padding: 5px;
            width: auto;
            height: auto;

        }
        </style>
        <div class="main-wrapper">
            <div class="header" style="background-color:#fff">
                <div class="header-left active" style="background-color:#fff">
                    <a href="<?= $this->basePath('/') ?>" class="logo" style="background-color:#fff">
                        <div class="logo-container">
                            <div class="logo-text">
                                <?php  
                                    if (isset($_SESSION['company'])) {
                                        echo htmlspecialchars($_SESSION['companyName'], ENT_QUOTES, 'UTF-8');
                                    }
                                ?>
                            </div>
                        </div>
                        <!-- <img src="<?= $this->basePath('img/logo.png') ?>" alt=""> -->
                    </a>
                    <a href="javascript:void(0);" class="logo-small">
                        <!-- <img src="<?= $this->basePath('img/logo-small.png') ?>" alt=""> -->
                    </a>
                    <a id="toggle_btn" href="javascript:void(0);">
                    </a>
                </div>

                <a id="mobile_btn" class="mobile_btn" href="#sidebar">
                    <span class="bar-icon">
                        <span></span>
                        <span></span>
                        <span></span>
                    </span>
                </a>

                <ul class="nav user-menu">

                    <li class="nav-item">
                        <div class="top-nav-search">
                            <a href="javascript:void(0);" class="responsive-search">
                                <i class="fa fa-search"></i>
                            </a>
                            <form action="#">
                                <div class="searchinputs">
                                    <input type="text" placeholder="Search Here ...">
                                    <div class="search-addon">
                                        <span><img src="<?= $this->basePath('img/icons/closes.svg') ?>"
                                                alt="img"></span>
                                    </div>
                                </div>
                                <a class="btn" id="searchdiv"><img src="<?= $this->basePath('img/icons/search.svg') ?>"
                                        alt="img"></a>
                            </form>
                        </div>
                    </li>


                    <li class="nav-item dropdown has-arrow flag-nav">
                        <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="javascript:void(0);"
                            role="button">
                            <img src="<?= $this->basePath('img/flags/us1.png') ?>" alt="" height="20">
                        </a>
                        <div class="dropdown-menu dropdown-menu-right">
                            <a href="javascript:void(0);" class="dropdown-item">
                                <img src="<?= $this->basePath('img/flags/us.png') ?>" alt="" height="16">
                                <?= $this->translation('English'); ?>
                            </a>
                            <a href="javascript:void(0);" class="dropdown-item">
                                <img src="<?= $this->basePath('img/flags/fr.png') ?>" alt="" height="16">
                                <?= $this->translation('French'); ?>
                            </a>
                            <a href="javascript:void(0);" class="dropdown-item">
                                <img src="<?= $this->basePath('img/flags/es.png') ?>" alt="" height="16">
                                <?= $this->translation('Spanish'); ?>
                            </a>
                            <a href="javascript:void(0);" class="dropdown-item">
                                <img src="<?= $this->basePath('img/flags/de.png') ?>" alt="" height="16">
                                <?= $this->translation('German'); ?>
                            </a>
                        </div>
                    </li>


                    <li class="nav-item dropdown">
                        <a href="javascript:void(0);" class="dropdown-toggle nav-link" data-bs-toggle="dropdown">
                            <img src="<?= $this->basePath('img/icons/notification-bing.svg') ?>" alt="img"> <span
                                class="badge rounded-pill">4</span>
                        </a>
                        <div class="dropdown-menu notifications">
                            <div class="topnav-dropdown-header">
                                <span class="notification-title"> <?= $this->translation('Notifications'); ?></span>
                                <a href="javascript:void(0)" class="clear-noti"> <?= $this->translation('Clear All'); ?>
                                </a>
                            </div>
                            <div class="noti-content">
                                <ul class="notification-list">
                                    <li class="notification-message">
                                        <a href="activities.html">
                                            <div class="media d-flex">
                                                <span class="avatar flex-shrink-0">
                                                    <img alt=""
                                                        src="<?= $this->basePath('img/profiles/avatar-02.jpg') ?>">
                                                </span>
                                                <div class="media-body flex-grow-1">
                                                    <p class="noti-details"><span class="noti-title">
                                                            <?php    // dd($_SESSION['company']);
                                                                if (isset($_SESSION['company'])) {
                                                                    echo htmlspecialchars($_SESSION['fullname'], ENT_QUOTES, 'UTF-8');
                                                                }
                                                                ?></span> <?= $this->translation(' added new task'); ?>
                                                        <span class="noti-title">
                                                            <?= $this->translation('Patient appointment
                                                            booking'); ?></span>
                                                    </p>
                                                    <p class="noti-time"><span class="notification-time">
                                                            <?= $this->translation('4 mins
                                                            ago'); ?></span>
                                                    </p>
                                                </div>
                                            </div>
                                        </a>
                                    </li>
                                    <li class="notification-message">
                                        <a href="activities.html">
                                            <div class="media d-flex">
                                                <span class="avatar flex-shrink-0">
                                                    <img alt=""
                                                        src="<?= $this->basePath('img/profiles/avatar-03.jpg') ?>">
                                                </span>
                                                <div class="media-body flex-grow-1">
                                                    <p class="noti-details"><span class="noti-title">
                                                            <?= $this->translation('Tarah Shropshire'); ?>
                                                        </span> <?= $this->translation('changed the task name'); ?>
                                                        <span class="noti-title">
                                                            <?= $this->translation('Appointment booking with payment gateway'); ?></span>
                                                    </p>
                                                    <p class="noti-time"><span class="notification-time">
                                                            <?= $this->translation('6 mins ago'); ?></span>
                                                    </p>
                                                </div>
                                            </div>
                                        </a>
                                    </li>
                                    <li class="notification-message">
                                        <a href="activities.html">
                                            <div class="media d-flex">
                                                <span class="avatar flex-shrink-0">
                                                    <img alt=""
                                                        src="<?= $this->basePath('img/profiles/avatar-06.jpg') ?>">
                                                </span>
                                                <div class="media-body flex-grow-1">
                                                    <p class="noti-details"><span class="noti-title">
                                                            <?= $this->translation('Misty Tison'); ?></span>
                                                        <?= $this->translation('added'); ?><span class="noti-title">
                                                            <?= $this->translation('Domenic Houston'); ?></span>
                                                        <?= $this->translation('and'); ?> <span class="noti-title">
                                                            <?= $this->translation('Claire Mapes'); ?></span>
                                                        <span class="noti-title">
                                                            <?= $this->translation('Doctor available module'); ?>
                                                        </span>
                                                    </p>
                                                    <p class="noti-time"><span class="notification-time">
                                                            <?= $this->translation('8 mins ago'); ?>
                                                        </span>
                                                    </p>
                                                </div>
                                            </div>
                                        </a>
                                    </li>
                                    <li class="notification-message">
                                        <a href="activities.html">

                                        </a>
                                    </li>
                                    <li class="notification-message">

                                    </li>
                                </ul>
                            </div>
                            <div class="topnav-dropdown-footer">
                                <a href="activities.html"> <?= $this->translation('View all Notifications'); ?></a>
                            </div>
                        </div>
                    </li>

                    <li class="nav-item dropdown has-arrow main-drop">
                        <a href="javascript:void(0);" class="dropdown-toggle nav-link userset"
                            data-bs-toggle="dropdown">
                            <span class="user-img"><img src="<?= $this->basePath('img/profiles/avator1.jpg') ?>" alt="">
                                <span class="status online"></span></span>
                        </a>
                        <div class="dropdown-menu menu-drop-user">
                            <div class="profilename">
                                <div class="profileset">
                                    <span class="user-img"><img src="<?= $this->basePath('img/profiles/avator1.jpg') ?>"
                                            alt="">
                                        <span class="status online"></span></span>
                                    <div class="profilesets">
                                        <h6> <?php    // dd($_SESSION['company']);
                                                if (isset($_SESSION['company'])) {
                                                    echo htmlspecialchars($_SESSION['company'][0]['fullname'], ENT_QUOTES, 'UTF-8');
                                                }
                                                ?></h6>
                                        <h5> <?= $this->translation('Admin'); ?></h5>
                                    </div>
                                </div>
                                <hr class="m-0">
                                <a class="dropdown-item" href="profile.html"> <i class="me-2" data-feather="user"></i>
                                    <?= $this->translation('My Profile'); ?>
                                </a>
                                <a class="dropdown-item" href="<?= $this->basePath('settings/edit') ?>"><i class="me-2"
                                        data-feather="settings"></i> <?= $this->translation('Settings'); ?></a>

                                <a class="dropdown-item " href="<?= $this->basePath('settings/selectcompany') ?>">
                                    <img src="<?= $this->basePath('img/icons/reversedark.svg') ?>" class="me-2"
                                        alt="img">
                                    <?= $this->translation(' Change Company '); ?>
                                </a>

                                <hr class="m-0">
                                <a class="dropdown-item logout pb-0" href="<?= $this->url('logout') ?>"><img
                                        src="<?= $this->basePath('img/icons/log-out.svg') ?>" class="me-2" alt="img">
                                    <?= $this->translation('Logout'); ?></a>




                            </div>
                        </div>
                    </li>
                </ul>


                <div class="dropdown mobile-user-menu">
                    <a href="javascript:void(0);" class="nav-link dropdown-toggle" data-bs-toggle="dropdown"
                        aria-expanded="false"><i class="fa fa-ellipsis-v"></i></a>
                    <div class="dropdown-menu dropdown-menu-right">
                        <a class="dropdown-item" href="profile.html"> <?= $this->translation('My Profile'); ?></a>
                        <a class="dropdown-item" href="generalsettings.html"> <?= $this->translation('Settings'); ?></a>
                        <a class="dropdown-item" href="signin.html"> <?= $this->translation('Logout'); ?></a>
                    </div>
                </div>

            </div>


            <div class="sidebar" id="sidebar">
                <div class="sidebar-inner slimscroll">
                    <div id="sidebar-menu" class="sidebar-menu">
                        <ul>
                            <li class="active">
                                <a href="<?= $this->basePath('/') ?>"><img
                                        src="<?= $this->basePath('img/icons/dashboard.svg') ?>" alt="img"><span>
                                        <?= $this->translation('Dashboard'); ?></span> </a>
                            </li>
                            <li class="submenu">
                                <a href="javascript:void(0);"><img src="<?= $this->basePath('img/icons/product.svg') ?>"
                                        alt="img"><span> <?= $this->translation('Products'); ?></span> <span
                                        class="menu-arrow"></span></a>
                                <ul>
                                    <li><a href="<?= $this->basePath('/products/list') ?>">
                                            <?= $this->translation('Product List'); ?></a></li>
                                    <li><a href="<?= $this->basePath('/products/add') ?>">
                                            <?= $this->translation('Add Product'); ?></a></li>
                                    <li><a href="<?= $this->basePath('/category/list') ?>">
                                            <?= $this->translation('Category'); ?></a></li>
                                    <li><a href="<?= $this->basePath('/settings/subcategory') ?>">
                                            <?= $this->translation('Sub Category List'); ?></a>
                                    </li>
                                    <li><a href="<?= $this->basePath('/settings/brand') ?>">
                                            <?= $this->translation('Brand List'); ?></a>
                                    </li>
                                    <li><a href="<?= $this->basePath('/products/import') ?>">
                                            <?= $this->translation('Import Products'); ?>
                                        </a></li>
                                    <li><a href="<?= $this->basePath('/products/codebare') ?>">
                                            <?= $this->translation('Print Barcode'); ?></a></li>
                                </ul>
                            </li>
                            <li class="submenu">
                                <a href="javascript:void(0);"><img src="<?= $this->basePath('img/icons/sales1.svg') ?>"
                                        alt="img"><span> <?= $this->translation('Sales'); ?></span> <span
                                        class="menu-arrow"></span></a>
                                <ul>
                                    <li><a href="<?= $this->basePath('/sales/list') ?>">
                                            <?= $this->translation('Bond delivery'); ?></a></li>
                                    <li><a href="<?= $this->basePath('/sales/listsales') ?>">
                                            <?= $this->translation('Sales List'); ?></a></li>
                                    <li><a href="<?= $this->basePath('/sales/list-estimate') ?>">
                                            <?= $this->translation('List Estimate'); ?></a></li>
                                    <li><a href="<?= $this->basePath('/settings/subcategory') ?>">
                                            <?= $this->translation('POS'); ?></a></li>
                                    <li><a href="<?= $this->basePath('/sales/add') ?>">
                                            <?= $this->translation('New Sales'); ?></a></li>
                                    <li><a href="<?= $this->basePath('/settings/subcategory') ?>">
                                            <?= $this->translation('Sales Return List'); ?></a>
                                    </li>
                                    <li><a href="<?= $this->basePath('/settings/subcategory') ?>">
                                            <?= $this->translation('New Sales Return'); ?></a>
                                    </li>
                                </ul>
                            </li>
                            <li class="submenu">
                                <a href="javascript:void(0);"><img src="<?= $this->basePath('img/icons/users1.svg') ?>"
                                        alt="img"><span>
                                        <?= $auth->translate('People'); ?></span> <span class="menu-arrow"></span></a>
                                <ul>
                                    <li><a href="<?= $this->basePath('/customers/list') ?>">
                                            <?= $auth->translate('Customer List'); ?></a></li>
                                    <!-- <li><a href="<?= $this->basePath('/settings/subcategory') ?>">Add Customer </a></li>
                                    <li><a href="<?= $this->basePath('/settings/subcategory') ?>">Supplier List</a></li>
                                    <li><a href="<?= $this->basePath('/settings/subcategory') ?>">Add Supplier </a></li>
                                    <li><a href="<?= $this->basePath('/settings/subcategory') ?>">User List</a></li>
                                    <li><a href="<?= $this->basePath('/settings/subcategory') ?>">Add User</a></li>
                                    <li><a href="<?= $this->basePath('/settings/subcategory') ?>">Store List</a></li>
                                    <li><a href="<?= $this->basePath('/settings/subcategory') ?>">Add Store</a></li> -->
                                </ul>
                            </li>
                            <li class="submenu">
                                <a href="javascript:void(0);"><img
                                        src="<?= $this->basePath('img/icons/settings.svg') ?>" alt="img"><span>
                                        <?= $this->translation('Settings'); ?></span> <span
                                        class="menu-arrow"></span></a>
                                <ul>
                                    <li><a href="<?= $this->basePath('settings/edit') ?>">
                                            <?= $this->translation('General Settings'); ?></a></li>
                                    <li><a href="<?= $this->basePath('settings/addcompanyinfo') ?>">
                                            <?= $this->translation('New company'); ?></a></li>
                                    <li><a href="<?= $this->basePath('settings/invoice') ?>">
                                            <?= $this->translation('Invoice Settings'); ?></a>
                                    </li>
                                    <li><a href="<?= $this->basePath('settings/langue') ?>">
                                            <?= $this->translation('Translate'); ?></a>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>

        </div>
        <?php
}
 

?>


        <script>
        function showCustomAlert(message) {
            document.getElementById('overlay').style.display = 'block';
            document.getElementById('customAlert').style.display = 'block';
            document.getElementById('customAlertMessage').textContent = message;
            setTimeout(closeCustomAlert, 2000);
        }

        function closeCustomAlert() {
            document.getElementById('overlay').style.display = 'none';
            document.getElementById('customAlert').style.display = 'none';
            location.reload();

        }
        </script>

        <?= $this->inlineScript()
                ->appendFile($this->basePath('js/jquery-3.6.0.min.js'))
                ->appendFile($this->basePath('js/feather.min.js'))
                ->appendFile($this->basePath('js/jquery.slimscroll.min.js'))
                ->appendFile($this->basePath('js/jquery.dataTables.min.js'))
                ->appendFile($this->basePath('js/dataTables.bootstrap4.min.js'))
                ->appendFile($this->basePath('js/bootstrap.bundle.min.js'))
                ->appendFile($this->basePath('plugins/apexchart/apexcharts.min.js'))
                ->appendFile($this->basePath('plugins/apexchart/chart-data.js'))
                ->appendFile($this->basePath('plugins/select2/js/select2.min.js'))
                ->appendFile($this->basePath('plugins/sweetalert/sweetalert2.all.min.js'))
                ->appendFile($this->basePath('plugins/sweetalert/sweetalerts.min.js'))
                ->appendFile($this->basePath('plugins/owlcarousel/owl.carousel.min.js')) 
                ->appendFile($this->basePath('js/script.js'));



                
?>

</html>