<div class="content" style="margin-top:80px;">
    <input type="text" id="basePath" style="display:none;" value="<?= $this->basePath() ?>">
    <div class="page-header">
        <div class="page-title">
            <h4>Sub Category List</h4>
            <h6>Manage your Sub Category </h6>
        </div>
        <div class="page-btn">
            <a class="btn btn-added addcategory" id="addcategory">
                <img src="<?= $this->basePath('img/icons/plus.svg') ?>" alt="img" class="me-1">Add New Element</a>
        </div>
    </div>

    <div class="card">
        <div class="card-body">
            <div class="table-top">
                <div class="search-set">
                    <div class="search-path">
                        <a class="btn btn-filter" id="filter_search">
                            <img src="<?= $this->basePath('img/icons/filter.svg') ?>" alt="img">
                            <span><img src="<?= $this->basePath('img/icons/closes.svg') ?>" alt="img"></span>
                        </a>
                    </div>
                    <div class="search-input">
                        <a class="btn btn-searchset"><img src="<?= $this->basePath('img/icons/search-white.svg') ?>"
                                alt="img"></a>
                    </div>
                </div>
                <div class="wordset">
                    <ul>
                        <li><a data-bs-toggle="tooltip" data-bs-placement="top" title="pdf"><img
                                    src="<?= $this->basePath('img/icons/pdf.svg') ?>" alt="img"></a></li>
                        <li><a data-bs-toggle="tooltip" data-bs-placement="top" title="excel"><img
                                    src="<?= $this->basePath('img/icons/excel.svg') ?>" alt="img"></a></li>
                        <li><a data-bs-toggle="tooltip" data-bs-placement="top" title="print"><img
                                    src="<?= $this->basePath('img/icons/printer.svg') ?>" alt="img"></a></li>
                    </ul>
                </div>
            </div>

            <!-- <div class="card mb-0" id="filter_inputs">
                <div class="card-body pb-0">
                    <div class="row">
                        <div class="col-lg-12 col-sm-12">
                            <div class="row">
                                <div class="col-lg col-sm-6 col-12">
                                    <div class="form-group">
                                        <select class="select">
                                            <option>Choose Product</option>
                                            <option>Macbook pro</option>
                                            <option>Orange</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-lg col-sm-6 col-12">
                                    <div class="form-group">
                                        <select class="select">
                                            <option>Choose Category</option>
                                            <option>Computers</option>
                                            <option>Fruits</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-lg col-sm-6 col-12">
                                    <div class="form-group">
                                        <select class="select">
                                            <option>Choose Sub Category</option>
                                            <option>Computer</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-lg col-sm-6 col-12">
                                    <div class="form-group">
                                        <select class="select">
                                            <option>Brand</option>
                                            <option>N/D</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-lg col-sm-6 col-12 ">
                                    <div class="form-group">
                                        <select class="select">
                                            <option>Price</option>
                                            <option>150.00</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-lg-1 col-sm-6 col-12">
                                    <div class="form-group">
                                        <a class="btn btn-filters ms-auto"><img
                                                src="<?= $this->basePath('img/icons/search-whites.svg') ?>"
                                                alt="img"></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div> -->

            <div class="table-responsive">
                <table class="table  datanew">
                    <thead>
                        <tr>
                            <th>
                                <label class="checkboxs">
                                    <input type="checkbox" id="select-all">
                                    <span class="checkmarks"></span>
                                </label>
                            </th>
                            <th>Sub Category Name</th>
                            <th>Category </th>
                            <th>Description </th>
                            <th>Created By</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($AllSubCategorys as $row ) { ?>
                        <tr>
                            <td>
                                <label class="checkboxs">
                                    <input type="checkbox">
                                    <span class="checkmarks"></span>
                                </label>
                            </td>
                            <td><?= $row['SubCategoryName'] ?></td>
                            <td> <?= $row['categoryname'] ?></td>
                            <td><?= $row['description'] ?></td>
                            <td> <?= $row['createdBy'] ?></td>
                            <td>

                                <a id="editbtn" class="mr-3 editbtn" data-item-id="<?= $row['id'] ?>"
                                    data-item-SubCategoryName="<?= $row['SubCategoryName'] ?>"
                                    data-item-categoryname="<?= $row['IdCategory'] ?>"
                                    data-item-description="<?= $row['description'] ?>">
                                    <img src="<?= $this->basePath('img/icons/edit.svg') ?>" alt="img">
                                </a>

                                <a class="deletebtn" data-item-id="<?= $row['id'] ?>">
                                    <img src="<?= $this->basePath('img/icons/delete.svg') ?>" alt="img">
                                </a>
                            </td>
                        </tr>
                        <?php } ?>

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<!-- add category Modal -->
<div class="modal fade" id="addcategoryModal" tabindex="-1" role="dialog" aria-labelledby="modelTitleId"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Add Sub Category</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form id="addsubcategoryForm">
                <div class="modal-body">

                    <label for="subcategoryname">Sub Category Name</label>
                    <input type="text" class="form-control" id="subcategoryname" required>

                    <label for="categoryname"> Select Category</label>
                    <select name="categoryname" class="form-control" id="categoryname">
                        <?php foreach ($this->Categorys as $row){ ?>
                        <option value="<?=  $row['id'];?>"><?=  $row['categoryName']; ?> </option>
                        <?php  }?>

                    </select>
                    <label for="description">Description</label>
                    <input type="text" class="form-control" id="description">

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal"
                        id="Closebtnaddcategory">Close</button>
                    <button type="submit" class="btn btn-primary" oncklick="validateForm()"
                        id="saveCategoryBtn">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>


<!-- edit category Modal -->
<div class="modal fade" id="editcategoryModal" tabindex="-1" role="dialog" aria-labelledby="modelTitleId"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" style="text-align:center">Edit Sub Category</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form id="editsubcategoryForm">
                <div class="modal-body">

                    <label for="categoryNameedit"> Select Category</label>
                    <select name="categoryNameedit" class="form-control" id="categoryNameedit">
                        <?php foreach ($this->Categorys as $row){ ?>
                        <option value="<?=  $row['id'];?>"><?=  $row['categoryName']; ?> </option>
                        <?php  }?>
                    </select>

                    <input type="text" class="form-control hidden " id="idsubcategory">

                    <label for="SubCategoryNameedit">Sub Category Name</label>
                    <input type="text" class="form-control" id="SubCategoryNameedit">

                    <label for="descriptionedit">Description</label>
                    <input type="text" class="form-control" id="descriptionedit">

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal"
                        id="Closebtnaddcategory">Close</button>
                    <button type="submit" class="btn btn-primary" oncklick="validateForm()"
                        id="saveCategoryBtn">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- delete sub category Modal -->

<div class="modal fade" id="deletecategoryModal" tabindex="-1" role="dialog" aria-labelledby="modelTitleId"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Delete Sub Category</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form id="deletecategoryForm">
                <div class="modal-body ">
                    <input type="text" class="form-control hidden" id="idsubcategorydelete">
                </div>
                <div class="center modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal"
                        id="Closebtnaddcategory">Close</button>
                    <button type="button" class="btn btn-primary" id="confirm">confirm</button>
                </div>
            </form>
        </div>
    </div>
</div>








<?= $this->inlineScript()->prependFile($this->basePath('js/jquery-3.6.0.min.js'));?>

<?php  $this->inlineScript() 
         ->appendFile($this->basePath('js/setting/scriptaddsubcategory.js'));